%% Reaction times
rxns_and_slopes = regressReactionTimes(dh, [start_time, size(dh.lfps,1)-30*1000]);
csvwrite(fullfile(data_dir, '../R/', 'rxns_and_slopes.csv'), ...
  [repelem(1:size(rxns_and_slopes,3), size(rxns_and_slopes,1))', ...
  reshape(permute(rxns_and_slopes,[1,3,2]), [], 2)]);